# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeonghyun's Blog
email: sungok88@naver.com
description: > # this means to ignore newlines until "baseurl:"
 Jeonghyun's Blog.
 Interested on A.I Platform and Android Framework.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jh20a.github.io" # the base hostname & protocol for your site
github_username:  jh20a

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

post_groups:
    - key: section
      group: sections
      exclude: ['Philosophy']
